#!/usr/bin/env bash

set -e

GO15VENDOREXPERIMENT=1 GOOS=linux go build 

cat nanobox-server | md5 >> nanobox-server.md5

s3cmd put --acl-public nanobox-server.md5 nanobox-server s3://tools.nanobox.io/server/linux/amd64/ 

rm nanobox-server.md5