#!/usr/bin/env bash
GOOS=linux gom build 

cat nanobox-server | md5 >> nanobox-server.md5

s3cmd put --acl-public nanobox-server.md5 nanobox-server s3://tools.nanobox.io/server/linux/amd64/ 

rm nanobox-server.md5